# Generated by Django 4.2 on 2024-10-16 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyComicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='calification',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
